### PR TITLE
pose2d and pose3d for json results

### PR DESCRIPTION
**Pull request by bhjelstrom**

### CODE REVIEW

**Comment by agasser** [comment]
Don't forget to update the version comment at the top of the file

**Comment by bhjelstrom** [comment]
This will happen per release! Should be good to go after this PR

**Comment by agasser** [comment]
Cool, but probably should work on a branch and only merge releases to main then. How would someone know when they should and shouldn't copy the code from main.

**Comment by bhjelstrom** [comment]
My thinking is only use the releases tab, or pull from main at your own risk (there is an actual .java asset per release). Thoughts?

**Comment by agasser** [comment]
I think that's probably fair, but there wasn't anything on the releases tab when I wrote the comment. You might want to mention that in the README and in the version comment at the top of the file (say it's pre-release). It's pretty common practice these days for `main` to always be in a releasable state, branches are used for work-in-progress.

**Pull request merged**
